name: ci.yml
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  loader:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: install loader dependencies
        run: pip install -r load/requirements-loader.txt

  trainer:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5

      - name: install trainer dependencies
        run: pip install -r train/requirements-trainer.txt